from setuptools import setup, find_packages

setup(
    name="evolve-core",
    version="0.1.0",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[],
    author="Wutong ASI",
    description="A self-evolving AI framework powered by genetic algorithms",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/zs001-agi/asi-evolve",
    license="MIT",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    keywords="evolutionary-algorithms genetic-algorithm self-evolving ai machine-learning",
)
