# Auto-generated by Wutong ASI agent
import random
from typing import List

class GeneticAlgorithm:
    def __init__(self, population_size, mutation_rate, crossover_rate):
        self.population = [random.randint(0, 1) for _ in range(population_size)]
        self.mutation_rate = mutation_rate
        self.crossover_rate = crossover_rate

    def evolve(self):
        new_population = []
        for i in range(len(self.population)):
            parent1, parent2 = random.sample(self.population, 2)
            child = self.crossover(parent1, parent2)
            if random.random() < self.mutation_rate:
                child = self.mutate(child)
            new_population.append(child)
        self.population = new_population

    def crossover(self, parent1: int, parent2: int) -> int:
        # Simple crossover, just swap the last bit
        return parent1 ^ parent2

    def mutate(self, individual: int) -> int:
        # Simple mutation, flip a random bit
        return individual ^ (1 << random.randint(0, 31))

    def evaluate(self):
        return sum(individual for individual in self.population)

# Example usage
ga = GeneticAlgorithm(population_size=200, mutation_rate=0.1, crossover_rate=0.8)
for _ in range(100):
    ga.evolve()
print(f"Best fitness: {ga.evaluate()}")