# Auto-generated by Wutong ASI agent
import random

class GeneticAlgorithm:
    def __init__(self, population_size, mutation_rate):
        self.population = [random.uniform(-1, 1) for _ in range(population_size)]
        self.mutation_rate = mutation_rate
    
    def evolve(self):
        new_population = []
        for _ in range(len(self.population)):
            parent1 = random.choice(self.population)
            parent2 = random.choice(self.population)
            offspring = self.crossover(parent1, parent2)
            offspring = self.mutate(offspring)
            new_population.append(offspring)
        self.population = new_population
    
    def crossover(self, parent1, parent2):
        return (parent1 + parent2) / 2
    
    def mutate(self, individual):
        for i in range(len(individual)):
            if random.random() < self.mutation_rate:
                individual[i] += random.uniform(-0.5, 0.5)
        return individual

# Example usage
ga = GeneticAlgorithm(100, 0.1)
for _ in range(100):
    ga.evolve()
print(ga.population)