# Auto-generated by Wutong ASI
import random

# Define the fitness function for evaluating solutions
def fitness(solution):
    """Compute fitness of an individual in a genetic algorithm based on given criteria."""
    return sum([x**2 for x in solution])

# Initialize population randomly
population = [[random.randint(-10, 10) for _ in range(5)] for __ in range(20)]

# Genetic algorithm parameters
generations = 100
mutation_rate = 0.1

# Evolution loop
for generation in range(generations):
    # Evaluate fitness of each individual
    population.sort(key=fitness)
    
    # Select the best individuals to reproduce
    next_gen = population[:5]
    
    # Perform crossover and mutation
    for _ in range(20 - 5):
        parent1, parent2 = random.sample(next_gen, 2)
        child = [parent1[i] if random.random() < 0.5 else parent2[i] for i in range(5)]
        
        # Mutation
        if random.random() < mutation_rate:
            mutate_index = random.randint(0, 4)
            child[mutate_index] += random.uniform(-1, 1)
        
        next_gen.append(child)
    
    population = next_gen

# Output the best solution found
best_solution = population[0]
print("Best Solution:", best_solution)
print("Fitness:", fitness(best_solution))